NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ab2.blockchaindev12.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ab2.blockchaindev12.com-cert.pem
    OrganizationalUnitIdentifier: peer
