NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.im1.blockchaindev12.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.im1.blockchaindev12.com-cert.pem
    OrganizationalUnitIdentifier: peer
