---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "balance-transfer"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Balance Transfer Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see im1.yaml and eb1.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  trade-instruction-channel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("im1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.blockchaindev12.com

    # Required. list of peers from participating orgs
    peers:
      peer0.im1.blockchaindev12.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.eb1.blockchaindev12.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.eb2.blockchaindev12.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.ab1.blockchaindev12.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.ab2.blockchaindev12.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.cb1.blockchaindev12.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true


    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  IM1:
    mspid: IM1

    peers:
      - peer0.im1.blockchaindev12.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-im1

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/im1.blockchaindev12.com/users/Admin@im1.blockchaindev12.com/msp/keystore/02551bb6dc10620052054a801b3e5c01cf8786f2a5e606ca2a37a67528c1d94f_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/im1.blockchaindev12.com/users/Admin@im1.blockchaindev12.com/msp/signcerts/Admin@im1.blockchaindev12.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  EB1:
    mspid: EB1
    peers:
      - peer0.eb1.blockchaindev12.com
    certificateAuthorities:
      - ca-eb1
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/eb1.blockchaindev12.com/users/Admin@eb1.blockchaindev12.com/msp/keystore/155dcb35d681a2affa5aacac3aceb9fda1397d38def2cce178e57802d0b4a273_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/eb1.blockchaindev12.com/users/Admin@eb1.blockchaindev12.com/msp/signcerts/Admin@eb1.blockchaindev12.com-cert.pem


  EB2:
    mspid: EB2
    peers:
      - peer0.eb2.blockchaindev12.com
    certificateAuthorities:
      - ca-eb2
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/eb2.blockchaindev12.com/users/Admin@eb2.blockchaindev12.com/msp/keystore/081cc2ea63438bba82e6699ecfa236ea29d4061f3dc85cebe63c92cc39ea2851_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/eb2.blockchaindev12.com/users/Admin@eb2.blockchaindev12.com/msp/signcerts/Admin@eb2.blockchaindev12.com-cert.pem

  AB1:
    mspid: AB1
    peers:
      - peer0.ab1.blockchaindev12.com
    certificateAuthorities:
      - ca-ab1
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/ab1.blockchaindev12.com/users/Admin@ab1.blockchaindev12.com/msp/keystore/801e8587e6771f5d4ce205a343861bb39fbd7f1ec145b872227fea492c32b85d_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/ab1.blockchaindev12.com/users/Admin@ab1.blockchaindev12.com/msp/signcerts/Admin@ab1.blockchaindev12.com-cert.pem

  AB2:
    mspid: AB2
    peers:
      - peer0.ab2.blockchaindev12.com
    certificateAuthorities:
      - ca-ab2
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/ab2.blockchaindev12.com/users/Admin@ab2.blockchaindev12.com/msp/keystore/8d99ded7b8a5e6341d43e8281354b1419f6dbe17e12ac78f76b3d87217fc0fe2_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/ab2.blockchaindev12.com/users/Admin@ab2.blockchaindev12.com/msp/signcerts/Admin@ab2.blockchaindev12.com-cert.pem

  CB1:
    mspid: CB1
    peers:
      - peer0.cb1.blockchaindev12.com
    certificateAuthorities:
      - ca-cb1
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/cb1.blockchaindev12.com/users/Admin@cb1.blockchaindev12.com/msp/keystore/e7f81f6b421bbb5cd1ea6f3019c74c341a4f2d91bc28fc329432149602d5bb79_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/cb1.blockchaindev12.com/users/Admin@cb1.blockchaindev12.com/msp/signcerts/Admin@cb1.blockchaindev12.com-cert.pem
  
#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.blockchaindev12.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.blockchaindev12.com

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/blockchaindev12.com/orderers/orderer.blockchaindev12.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.im1.blockchaindev12.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.im1.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/im1.blockchaindev12.com/peers/peer0.im1.blockchaindev12.com/tls/ca.crt

  peer0.eb1.blockchaindev12.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.eb1.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/eb1.blockchaindev12.com/peers/peer0.eb1.blockchaindev12.com/tls/ca.crt

  peer0.eb2.blockchaindev12.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.eb2.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/eb2.blockchaindev12.com/peers/peer0.eb2.blockchaindev12.com/tls/ca.crt

  peer0.ab1.blockchaindev12.com:
    url: grpcs://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer0.ab1.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/ab1.blockchaindev12.com/peers/peer0.ab1.blockchaindev12.com/tls/ca.crt
  peer0.ab2.blockchaindev12.com:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.ab2.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/ab2.blockchaindev12.com/peers/peer0.ab2.blockchaindev12.com/tls/ca.crt

  peer0.cb1.blockchaindev12.com:
    url: grpcs://localhost:12051
    grpcOptions:
      ssl-target-name-override: peer0.cb1.blockchaindev12.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/cb1.blockchaindev12.com/peers/peer0.cb1.blockchaindev12.com/tls/ca.crt
#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-im1:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/im1.blockchaindev12.com/ca/ca.im1.blockchaindev12.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-im1

  ca-eb1:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/eb1.blockchaindev12.com/ca/ca.eb1.blockchaindev12.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-eb1

  ca-eb2:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/eb2.blockchaindev12.com/ca/ca.eb2.blockchaindev12.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-eb2

  ca-ab1:
    url: https://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/ab1.blockchaindev12.com/ca/ca.ab1.blockchaindev12.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-ab1

  ca-ab2:
    url: https://localhost:11054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/ab2.blockchaindev12.com/ca/ca.ab2.blockchaindev12.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-ab2

  ca-cb1:
    url: https://localhost:12054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/cb1.blockchaindev12.com/ca/ca.cb1.blockchaindev12.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-cb1